stages:
  always_run:
    cmd: python rough/test.py
  load_data:
    cmd: python src/stage_1_load_save.py --config=config/config.yaml
    deps:
      - src/stage_1_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
      - rough/test.txt
    outs:
      - artifacts/raw_local_dir/data.csv

  split_data:
    cmd: python src/stage_02_split_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
      - artifacts/raw_local_dir/data.csv
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv

  train_data:
    cmd: python src/stage_03_train.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train.py
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
    params:
      - model_params.Elastic_net.alpha
      - model_params.Elastic_net.l1_ratio
      - model_params.Elastic_net.random_state_elastic
    outs:
      - artifacts/model_dir/model.pkl

  evaluate:
    cmd: python src/stage_04_evaluate.py --config=config/config.yaml
    deps:
      - src/stage_04_evaluate.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/test.csv
      - artifacts/model_dir/model.pkl
    outs:
      - artifacts/report_dir/report.json




