stages:
  load_data:
    cmd: python src/stage_1_load_sace.py --config=config.yaml
    deps:
      -src/stage_1_load_save.py
      -src/utils/all_utils.py
      -config/config.yaml
    outs:
      -artifacts/raw_local_dir/data.csv
